name: "Publish project"

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        required: false
        type: string
        default: sandbox
      app-name:
        required: true
        description: Name of application
        type: string
        default: 'no-name'
      s3-report-bucket:
        required: false
        description: S3 report bucket name
        type: string
        default: 'com.lyricfinancial.drone-reports'
      repo-owner:
        required: false
        description: Github repository owner
        type: string
        default: 'LyricFinancial'
    secrets:
      slack_webhook_url:
        required: true

jobs:
  notify:
    name: "Send workflow status to Slack"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: "Build Failure status"
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            { 
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                    "type": "mrkdwn",
                    "text": "Workflow *${{ inputs.app-name }} package build* failed from `${{ github.ref_name }}`"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "Click here to see errors: https://s3.console.aws.amazon.com/s3/object/${{ inputs.s3-report-bucket }}/${{ inputs.repo-owner }}/${{ inputs.app-name }}/${{ github.run_number }}/testResults.zip?region=us-east-1&tab=overview"
                    }
                  ]  
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "`Status` : *Failed* :x:"
                    }
                  ]
                }
              ]
            }
